DROP TABLE dbo.HOTEL_FACILITIES
DROP TABLE dbo.ROOM_FACILITIES
DROP TABLE dbo.ROOMS
DROP TABLE dbo.FACILITIES
DROP TABLE dbo.LOCALITIES
DROP TABLE dbo.HOTELS
GO

CREATE TABLE dbo.FACILITIES(
    ID              INT IDENTITY PRIMARY KEY,
    DISPLAY_NAME    VARCHAR(50),
    IS_ACTIVE       SMALLINT,
    VERSION         INT
)
GO

CREATE TABLE dbo.ROOMS(
    ID              INT IDENTITY PRIMARY KEY,
    HOTEL_ID        INT,
    NAME            VARCHAR(255),
    QUANTITY        INT,
    MAX_PRICE       INT,
    MIN_PRICE       INT,
    IS_ACTIVE       SMALLINT,
    VERSION         INT
)
GO

CREATE TABLE dbo.LOCALITIES(
    ID              INT IDENTITY PRIMARY KEY,
    NAME            VARCHAR(100),
    CITY_ID         INT,
    STATE_ID        INT,
    COUNTRY_ID      INT,
    ZIPCODE         INT,
    IS_ACTIVE       SMALLINT,
    VERSION         INT
)
GO

CREATE TABLE dbo.HOTELS(
    ID              INT IDENTITY PRIMARY KEY,
    NAME            VARCHAR(50),
    DESCRIPTION     VARCHAR(100),
    LOCALITY_ID     INT,
    ORIGINAL_IMAGE_PATH     VARCHAR(255),
    DISPLAY_IMAGE_PATH      VARCHAR(255),
    IS_ACTIVE       SMALLINT,
    VERSION         INT
)
GO

CREATE TABLE dbo.HOTEL_FACILITIES(
    ID              INT IDENTITY PRIMARY KEY,
    HOTEL_ID        INT,
    FACILITY_ID     INT,
    IS_ACTIVE       SMALLINT,
    VERSION         INT
)
GO

CREATE TABLE dbo.ROOM_FACILITIES(
    ID              INT IDENTITY PRIMARY KEY,
    ROOM_ID         INT,
    FACILITY_ID     INT,
    IS_ACTIVE       SMALLINT,
    VERSION         INT
)
GO

ALTER TABLE dbo.HOTEL_FACILITIES ADD CONSTRAINT FK_HOTEL_FACILITIES_TO_HOTELS FOREIGN KEY (HOTEL_ID) REFERENCES dbo.HOTELS(ID)
GO

ALTER TABLE dbo.HOTEL_FACILITIES ADD CONSTRAINT FK_HOTEL_FACILITIES_TO_FACILITIES FOREIGN KEY (FACILITY_ID) REFERENCES dbo.FACILITIES(ID)
GO

ALTER TABLE dbo.ROOM_FACILITIES ADD CONSTRAINT FK_ROOM_FACILITIES_TO_ROOMS FOREIGN KEY (ROOM_ID) REFERENCES dbo.ROOMS(ID)
GO

ALTER TABLE dbo.ROOM_FACILITIES ADD CONSTRAINT FK_ROOM_FACILITIES_TO_FACILITIES FOREIGN KEY (FACILITY_ID) REFERENCES dbo.FACILITIES(ID)
GO

ALTER TABLE dbo.ROOMS ADD CONSTRAINT FK_ROOMS_HOTELS FOREIGN KEY (HOTEL_ID) REFERENCES dbo.HOTELS(ID)
GO


/*******************************
* Data loading
************/

INSERT INTO dbo.FACILITIES VALUES 
    ('Dining', 1, 0),
    ('Transport Facility', 1, 0),
    ('Swimming Pool', 1, 0),
    ('Wifi', 1, 0),
    ('Drinks', 1, 0),
    ('TV', 1, 0),
    ('Coffee', 1, 0)

INSERT INTO dbo.LOCALITIES VALUES 
    ('Chanda Nagar', 1, 1, 1, 500001, 1, 0),
    ('Kukatpally Y Junction', 1, 1, 1, 500011, 1, 0),
    ('Nallagandla, Ratnadeep', 1, 1, 1, 500012, 1, 0),
    ('Aparna Road', 1, 1, 1, 500013, 1, 0)


/************
* Check
*************/

SELECT * FROM dbo.FACILITIES
SELECT * FROM dbo.LOCALITIES
GO